// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/cubits/medicine_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/data/models/medicine_plan.dart' as _i6;
import 'package:frontend/data/models/medicine_tracking.dart' as _i5;
import 'package:frontend/data/repositories/medicine_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MedicineRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicineRepository extends _i1.Mock
    implements _i3.MedicineRepository {
  MockMedicineRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get dbFuture =>
      (super.noSuchMethod(
            Invocation.getter(#dbFuture),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#dbFuture)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<void> saveMedicine({
    required _i5.MedicineTracking? tracking,
    required _i6.MedicinePlan? plan,
    required List<String>? times,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveMedicine, [], {
              #tracking: tracking,
              #plan: plan,
              #times: times,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.MedicinePlan?> getPlanById(int? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanById, [planId]),
            returnValue: _i4.Future<_i6.MedicinePlan?>.value(),
          )
          as _i4.Future<_i6.MedicinePlan?>);

  @override
  _i4.Future<_i5.MedicineTracking?> getTrackingById(int? trackingId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackingById, [trackingId]),
            returnValue: _i4.Future<_i5.MedicineTracking?>.value(),
          )
          as _i4.Future<_i5.MedicineTracking?>);

  @override
  _i4.Future<bool> updateMedicineTracking(_i5.MedicineTracking? tracking) =>
      (super.noSuchMethod(
            Invocation.method(#updateMedicineTracking, [tracking]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateMedicinePlan(_i6.MedicinePlan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#updateMedicinePlan, [plan]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteMedicinePlan(int? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMedicinePlan, [planId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> regenerateOccurrences({
    required int? planId,
    required DateTime? startDate,
    required DateTime? endDate,
    required List<String>? times,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#regenerateOccurrences, [], {
              #planId: planId,
              #startDate: startDate,
              #endDate: endDate,
              #times: times,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
