// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/unit_tests.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:frontend/data/models/user.dart' as _i13;
import 'package:frontend/data/repositories/user_repo.dart' as _i11;
import 'package:frontend/data/services/api/auth_api_service.dart' as _i2;
import 'package:frontend/data/services/api/medication_log_api_service.dart'
    as _i7;
import 'package:frontend/data/services/api/medicine_api_service.dart' as _i4;
import 'package:frontend/data/services/api/pharmacy_api_service.dart' as _i5;
import 'package:frontend/data/services/api/reservation_api_service.dart' as _i6;
import 'package:frontend/data/services/api/statistics_api_service.dart' as _i8;
import 'package:frontend/data/services/api/sync_api_service.dart' as _i9;
import 'package:frontend/data/services/api/user_api_service.dart' as _i3;
import 'package:frontend/data/services/api_service.dart' as _i14;
import 'package:frontend/data/services/sync_service.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthApiService_0 extends _i1.SmartFake
    implements _i2.AuthApiService {
  _FakeAuthApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserApiService_1 extends _i1.SmartFake
    implements _i3.UserApiService {
  _FakeUserApiService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMedicineApiService_2 extends _i1.SmartFake
    implements _i4.MedicineApiService {
  _FakeMedicineApiService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePharmacyApiService_3 extends _i1.SmartFake
    implements _i5.PharmacyApiService {
  _FakePharmacyApiService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReservationApiService_4 extends _i1.SmartFake
    implements _i6.ReservationApiService {
  _FakeReservationApiService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMedicationLogApiService_5 extends _i1.SmartFake
    implements _i7.MedicationLogApiService {
  _FakeMedicationLogApiService_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStatisticsApiService_6 extends _i1.SmartFake
    implements _i8.StatisticsApiService {
  _FakeStatisticsApiService_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncApiService_7 extends _i1.SmartFake
    implements _i9.SyncApiService {
  _FakeSyncApiService_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncResult_8 extends _i1.SmartFake implements _i10.SyncResult {
  _FakeSyncResult_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i11.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<int> insertUser(_i13.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#insertUser, [user]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<_i13.User?> getUserById(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i12.Future<_i13.User?>.value(),
          )
          as _i12.Future<_i13.User?>);

  @override
  _i12.Future<_i13.User?> getUserByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByEmail, [email]),
            returnValue: _i12.Future<_i13.User?>.value(),
          )
          as _i12.Future<_i13.User?>);

  @override
  _i12.Future<_i13.User?> getUserByPhone(String? phone) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByPhone, [phone]),
            returnValue: _i12.Future<_i13.User?>.value(),
          )
          as _i12.Future<_i13.User?>);

  @override
  _i12.Future<List<_i13.User>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i12.Future<List<_i13.User>>.value(<_i13.User>[]),
          )
          as _i12.Future<List<_i13.User>>);

  @override
  _i12.Future<int> updateUser(_i13.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> updateUserLocation(
    int? userId,
    double? latitude,
    double? longitude, {
    String? locationName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUserLocation,
              [userId, latitude, longitude],
              {#locationName: locationName},
            ),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> updateUserPremium(int? userId, bool? premium) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserPremium, [userId, premium]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<bool> emailExists(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#emailExists, [email]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> phoneExists(String? phone) =>
      (super.noSuchMethod(
            Invocation.method(#phoneExists, [phone]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<_i13.User?> authenticateUser(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#authenticateUser, [email, password]),
            returnValue: _i12.Future<_i13.User?>.value(),
          )
          as _i12.Future<_i13.User?>);

  @override
  _i12.Future<List<_i13.User>> getPremiumUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getPremiumUsers, []),
            returnValue: _i12.Future<List<_i13.User>>.value(<_i13.User>[]),
          )
          as _i12.Future<List<_i13.User>>);

  @override
  _i12.Future<int> getUserCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUserCount, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllUsers, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteUserByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserByEmail, [email]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteUserById(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserById, [userId]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteUserByPhone(String? phone) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserByPhone, [phone]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i14.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthApiService get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuthApiService_0(this, Invocation.getter(#auth)),
          )
          as _i2.AuthApiService);

  @override
  _i3.UserApiService get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _FakeUserApiService_1(this, Invocation.getter(#users)),
          )
          as _i3.UserApiService);

  @override
  _i4.MedicineApiService get medicines =>
      (super.noSuchMethod(
            Invocation.getter(#medicines),
            returnValue: _FakeMedicineApiService_2(
              this,
              Invocation.getter(#medicines),
            ),
          )
          as _i4.MedicineApiService);

  @override
  _i5.PharmacyApiService get pharmacies =>
      (super.noSuchMethod(
            Invocation.getter(#pharmacies),
            returnValue: _FakePharmacyApiService_3(
              this,
              Invocation.getter(#pharmacies),
            ),
          )
          as _i5.PharmacyApiService);

  @override
  _i6.ReservationApiService get reservations =>
      (super.noSuchMethod(
            Invocation.getter(#reservations),
            returnValue: _FakeReservationApiService_4(
              this,
              Invocation.getter(#reservations),
            ),
          )
          as _i6.ReservationApiService);

  @override
  _i7.MedicationLogApiService get medicationLogs =>
      (super.noSuchMethod(
            Invocation.getter(#medicationLogs),
            returnValue: _FakeMedicationLogApiService_5(
              this,
              Invocation.getter(#medicationLogs),
            ),
          )
          as _i7.MedicationLogApiService);

  @override
  _i8.StatisticsApiService get statistics =>
      (super.noSuchMethod(
            Invocation.getter(#statistics),
            returnValue: _FakeStatisticsApiService_6(
              this,
              Invocation.getter(#statistics),
            ),
          )
          as _i8.StatisticsApiService);

  @override
  _i9.SyncApiService get sync =>
      (super.noSuchMethod(
            Invocation.getter(#sync),
            returnValue: _FakeSyncApiService_7(this, Invocation.getter(#sync)),
          )
          as _i9.SyncApiService);

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
    Invocation.method(#setAuthToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void clearAuthToken() => super.noSuchMethod(
    Invocation.method(#clearAuthToken, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<Map<String, dynamic>> register(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#register, [userData]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<Map<String, dynamic>> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<Map<String, dynamic>> verifyUser(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#verifyUser, [email]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<Map<String, dynamic>> createUser(
    Map<String, dynamic>? userData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [userData]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<Map<String, dynamic>> getUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<Map<String, dynamic>> updateUser(
    int? userId,
    Map<String, dynamic>? userData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [userId, userData]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<void> updateFCMToken(int? userId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#updateFCMToken, [userId, token]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<dynamic>> getMedicines(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMedicines, [userId]),
            returnValue: _i12.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i12.Future<List<dynamic>>);

  @override
  _i12.Future<Map<String, dynamic>> createMedicine(
    Map<String, dynamic>? medicineData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMedicine, [medicineData]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<Map<String, dynamic>> updateMedicine(
    int? medicineId,
    Map<String, dynamic>? medicineData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMedicine, [medicineId, medicineData]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<void> deleteMedicine(int? medicineId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMedicine, [medicineId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<Map<String, dynamic>> createReservation(
    Map<String, dynamic>? reservationData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createReservation, [reservationData]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<List<dynamic>> getReservations(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getReservations, [userId]),
            returnValue: _i12.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i12.Future<List<dynamic>>);

  @override
  _i12.Future<Map<String, dynamic>> updateReservationStatus(
    int? reservationId,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateReservationStatus, [
              reservationId,
              status,
            ]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<Map<String, dynamic>> logMedicationIntake(
    Map<String, dynamic>? logData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logMedicationIntake, [logData]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<List<dynamic>> getMedicationLogs(
    int? userId, {
    String? startDate,
    String? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMedicationLogs,
              [userId],
              {#startDate: startDate, #endDate: endDate},
            ),
            returnValue: _i12.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i12.Future<List<dynamic>>);

  @override
  _i12.Future<Map<String, dynamic>> getAdherenceStats(
    int? userId, {
    String? period,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAdherenceStats, [userId], {#period: period}),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<Map<String, dynamic>> syncData(Map<String, dynamic>? syncData) =>
      (super.noSuchMethod(
            Invocation.method(#syncData, [syncData]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i10.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSyncing =>
      (super.noSuchMethod(Invocation.getter(#isSyncing), returnValue: false)
          as bool);

  @override
  _i12.Future<bool> hasConnection() =>
      (super.noSuchMethod(
            Invocation.method(#hasConnection, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<_i10.SyncResult> syncAll(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#syncAll, [userId]),
            returnValue: _i12.Future<_i10.SyncResult>.value(
              _FakeSyncResult_8(this, Invocation.method(#syncAll, [userId])),
            ),
          )
          as _i12.Future<_i10.SyncResult>);

  @override
  _i12.Future<bool> pushItem(String? table, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#pushItem, [table, data]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);
}
