// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb0O4wxk9eRovVwX2KtRx2QeySr1-gwB8',
    appId: '1:314680386568:web:5ee67a7abdee1a30a8ddbd',
    messagingSenderId: '314680386568',
    projectId: 'medigo-2bc1eg8s2',
    authDomain: 'medigo-2bc1eg8s2.firebaseapp.com',
    storageBucket: 'medigo-2bc1eg8s2.firebasestorage.app',
    measurementId: 'G-VBY6099EB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR4q5HhV7POFOZfNnOhDs47s4sxrBWo9E',
    appId: '1:314680386568:android:25d66f59dfface79a8ddbd',
    messagingSenderId: '314680386568',
    projectId: 'medigo-2bc1eg8s2',
    storageBucket: 'medigo-2bc1eg8s2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlZ34U3nKaJpxVnp9eJiG9JNzE1pO1AFY',
    appId: '1:314680386568:ios:fe804a50d6382c80a8ddbd',
    messagingSenderId: '314680386568',
    projectId: 'medigo-2bc1eg8s2',
    storageBucket: 'medigo-2bc1eg8s2.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlZ34U3nKaJpxVnp9eJiG9JNzE1pO1AFY',
    appId: '1:314680386568:ios:fe804a50d6382c80a8ddbd',
    messagingSenderId: '314680386568',
    projectId: 'medigo-2bc1eg8s2',
    storageBucket: 'medigo-2bc1eg8s2.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb0O4wxk9eRovVwX2KtRx2QeySr1-gwB8',
    appId: '1:314680386568:web:3435416b4e202c26a8ddbd',
    messagingSenderId: '314680386568',
    projectId: 'medigo-2bc1eg8s2',
    authDomain: 'medigo-2bc1eg8s2.firebaseapp.com',
    storageBucket: 'medigo-2bc1eg8s2.firebasestorage.app',
    measurementId: 'G-GH1DKLD0P7',
  );
}
